spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-9323263.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oad5396lBEI2sVhv5d6
            client-secret: xjmJiYM4HuH48CJZ-4QMQS9ZOSUCGhrzade4ONmf
