spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-9323263.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oanmx12wGZL7y1MS5d6
            client-secret: SSb6owe6EVRSQPlviH4_vtWvlsZQkekncbqE6Ys8
