spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-2530788.okta.com/oauth2/default 
        registration:
          oidc:
            client-id: 0oa1gf35u8K1k8TFP5d7 
            client-secret: "{cipher}23b2e77c75cf4deda06bb1d5dd62a47ed6b5797e611ccb7e40b8e56c4c3c2e056eb5df5c3fb60e977873763cf56dc2e3ffe8afa715bd8df488ac61e606bbae04"
