spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-1106225.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oapdlc1jbTQsin5h5d6 
            client-secret: "{cipher}3a21c8fb4814691e7e8d8d5c8e018d33c05e9dcc27665967682d9aaebf8b2a0fb71699e84c293d3a0ad60fdc9833c251f426b0a0141d353d0f8d1f802e45ecd4"
